### ISSUE TITLE
"The team" menu item not clickable. No href value. 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/forum.joomla.org#1]
<img width="665" alt="Screenshot 2020-09-16 at 13 42 02" src="https://user-images.githubusercontent.com/400092/93338757-9cb67080-f822-11ea-9fc8-aeb0cb27e992.png">
<img width="400" alt="Screenshot 2020-09-16 at 13 43 39" src="https://user-images.githubusercontent.com/400092/93338778-a50eab80-f822-11ea-8795-78c08c8a49c0.png">

**Comment by ooffick** [comment]
Sorry about the delay, I was not monitoring this. This is fixed now, if you login it was always working.

**Comment by conconnl** [comment]
Old issue and answered that it was fixed.
Therefore closing it.
